# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#workspace 'hotmoto.xcworkspace' # Your project's workspace
#project 'hotmoto.xcodeproj' # Your project's Xcode project
#project 'Frameworks/External/PXGoogleDirections/PXGoogleDirections.xcodeproj' # Update folder structure if needed



target 'MotoPark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  project 'hotmoto.xcodeproj'
  platform :ios, '10.0'
  use_frameworks!

  # Pods for hotmoto
  pod 'Alamofire'
#  pod 'GoogleMaps'
#  pod 'GooglePlaces'
#  pod 'GooglePlacePicker', '= 2.7.0'
   pod 'AlamofireImage'
   pod 'PXGoogleDirections'
   pod 'TPKeyboardAvoidingSwift'
   pod 'Cloudinary'
   pod 'KMPlaceholderTextView'
   pod 'PureLayout'
   pod 'JGProgressHUD'

end

